change artifact upload path

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,6 +28,9 @@ jobs:
       - name: build project
         run: npm run build
 
+      - name: List .next contents
+        run: ls -R .next || echo ".next not found"
+
       - name: upload build artifact
         uses: actions/upload-artifact@v4
         with:
